// tools/tenant-isolation-lint/report.ts
//
// Generates tenant-isolation-exceptions.md from scan results.
// CI diffs the generated file against the committed version.

import * as fs from 'fs';
import type { DisableAnnotation } from './detect.js';
import { DIRECTORY_ALLOWLIST } from './config.js';

const REPORT_PATH = 'tenant-isolation-exceptions.md';

export function generateReport(annotations: DisableAnnotation[]): string {
  const lines: string[] = [
    '# Tenant Isolation Exceptions',
    '',
    '_Auto-generated by tools/tenant-isolation-lint. Do not edit manually._',
    '',
  ];

  // Per-line exceptions
  lines.push('## Per-line exceptions');
  lines.push('');

  if (annotations.length === 0) {
    lines.push('_No per-line exceptions._');
  } else {
    // Sort by file then line
    const sorted = [...annotations].sort((a, b) =>
      a.file.localeCompare(b.file) || a.line - b.line
    );
    for (const ann of sorted) {
      lines.push(`- \`${ann.file}:${ann.coversLine}\` — "${ann.reason}"`);
    }
  }

  lines.push('');
  lines.push('## Directory allowlists');
  lines.push('');

  for (const [path, reason] of Object.entries(DIRECTORY_ALLOWLIST)) {
    lines.push(`- \`${path}\` — "${reason}"`);
  }

  lines.push('');
  return lines.join('\n');
}

export function writeReport(annotations: DisableAnnotation[]): void {
  const content = generateReport(annotations);
  fs.writeFileSync(REPORT_PATH, content);
}

export function diffReport(annotations: DisableAnnotation[]): { hasDiff: boolean; diff: string } {
  const expected = generateReport(annotations);

  if (!fs.existsSync(REPORT_PATH)) {
    return {
      hasDiff: true,
      diff: `File ${REPORT_PATH} does not exist. Run the gate with --write to generate it.`,
    };
  }

  const current = fs.readFileSync(REPORT_PATH, 'utf-8');

  if (current === expected) {
    return { hasDiff: false, diff: '' };
  }

  // Simple line-by-line diff for CI output
  const currentLines = current.split('\n');
  const expectedLines = expected.split('\n');
  const diffLines: string[] = [];

  const maxLen = Math.max(currentLines.length, expectedLines.length);
  for (let i = 0; i < maxLen; i++) {
    const cur = currentLines[i] ?? '';
    const exp = expectedLines[i] ?? '';
    if (cur !== exp) {
      if (cur) diffLines.push(`- ${cur}`);
      if (exp) diffLines.push(`+ ${exp}`);
    }
  }

  return {
    hasDiff: true,
    diff: `${REPORT_PATH} is out of date. Differences:\n${diffLines.join('\n')}\n\nRun the gate with --write to regenerate.`,
  };
}
