import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { auth } from '@/auth';
import { SignOut } from '@/components/sign-out';
import Link from 'next/link';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-4 border-b flex justify-between items-center bg-white">
          <Link href="/" className="font-bold text-xl">PropManager DE</Link>
          <div>
            {session?.user ? (
              <div className="flex gap-4 items-center">
                <span className="text-sm">Willkommen, {session.user.name || session.user.email}</span>
                <SignOut />
              </div>
            ) : (
              <Link href="/login" className="text-sm font-medium hover:underline">Login</Link>
            )}
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
